### ISSUE TITLE
Could you please help with build script panic

### ISSUE THREAD

**Issue by vit1251** [Slabity/modesetting-rs#1]
Try compile example and meet with next issue:

```
  --- stderr
  thread 'main' panicked at 'Box<dyn Any>', ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/modesetting-0.2.2/build.rs:17:19
```

Any idea how to detect root cause of this issue?

**Comment by Slabity** [comment]
Hi @vit1251, this crate is unfortunately not maintained anymore. Instead, I highly recommend using the [drm-rs](https://github.com/Smithay/drm-rs) crate, which provides a thin layer to the Direct Rendering Manager's modesetting capabilities. It was created specifically to avoid the issues I had when developing this crate.

I have been looking at recreating this crate to provide higher-level functionality on top of `drm-rs`, but that work has not yet been done.

**Comment by vit1251** [comment]
Sad news, and I have already decided to contribute to the update. Well, okay, let's look at drm-rs. In any case, thanks for the quick response.
